### ISSUE TITLE
unable to change clientoptions path and set a callbackfunction to score

### ISSUE THREAD

**Issue by Bhoft** [yii2mod/yii2-star-rating#1]
I would recommend to change the setting of the path for the star images
    
    if (!isset($this->clientOptions['path'])) {
       $this->clientOptions['path'] = $assetBundle->baseUrl . $this->path;
    }

and have a public variable 

     public $path = '/lib/images';

with this change it is possible to set the $path to `'/demo/images',`  to use the images which are coming with the assetsbundle.

And you also have the possibility to set 

    'clientOptions' => [
      'path' =>  yii\helpers\Url::to('@web/img/startrating'),
    ]
if you want to use star images e.g. from a public web folder.

Another change is that the client-options score value also shouldn't be set if already set.
E.g. if i want to set the score by some callback function.

    'score' => new JsExpression("function(){var score = $(this).attr('data-score'); console.log(['score', score]; return score;}"),

So i would recommend also to only set the clientOptions['score'] if it isn't set already.

**Comment by ihorchepurnyi** [comment]
Hi, can you create PR for this feature?
